export const RENDER_REAGENTS = 'RENDER_REAGENTS' // x
export const REAGENTS_FAILED = 'REAGENTS_FALED' //
export const ADD_REAGENTS = 'ADD_REAGENTS' // x
export const UPDATE_REAGENTS = 'UPDATE_REAGENTS'
export const REMOVE_REAGENTS = 'REMOVE_REAGENTS' // x
export const RENDER_SEC_REAGENTS = 'RENDER_SEC_REAGENTS'
export const SEC_REAGENTS_FAILED = 'SEC_REAGENTS_FAILED' //
export const UPDATE_SEC_REAGENTS = 'UPDATE_SEC_REAGENTS'
export const REMOVE_SEC_REAGENTS = 'REMOVE_SEC_REAGENTS'
export const RENDER_TESTS = 'RENDER_TESTS' // x
export const TESTS_FAILED = 'TESTS_FAILED' // 
export const REMOVE_TESTS = 'REMOVE_TESTS' // x
export const SWITCH_TESTS = 'SWITCH_TESTS' // x
export const RENDER_TESTTYPES = 'RENDER_TESTTYPES'
export const TESTTYPES_FAILED = 'TESTTYPES_FAILED' // 
export const ADD_TESTTYPE = 'ADD_TESTTYPE'
export const REMOVE_TESTTYPE = 'REMOVE_TESTTYPE'

