export const RENDER_REAGENTS = 'RENDER_REAGENTS'
export const ADD_REAGENTS = 'ADD_REAGENTS'
export const REAGENTS_FAILED = 'REAGENTS_FAILED'
export const REMOVE_REAGENTS = 'REMOVE_REAGENTS'
export const RENDER_TESTS = 'RENDER_TESTS'
export const TESTS_FAILED = 'RENDER_TESTS'
export const SWITCH_TESTS = 'SWITCH_TESTS'

